### ISSUE TITLE
Build CSS with CI

### ISSUE THREAD

**Issue by BcRikko** [nostalgic-css/NES.css#13]
cssファイルがコンフリクトしてしまうので、masterにマージしたときにCIでビルドしたい

**Comment by BcRikko** [comment]
## Travis CI

> Always free for open source projects
https://travis-ci.com/plans

## Circle CI

> 1,000 build minutes per month
https://circleci.com/pricing/

**Comment by trezy** [comment]
@BcRikko Have you already started on this? If not, I'd love to help out. I'll fork this afternoon and get it set up on CircleCI if that works for you.

I also have a few suggestions that would make it easier to manage the community that you're very swiftly building.

1. **Create a `develop` branch**
  Many large repositories have a `develop` branch for people to merge their pull requests into. This allows the original repo to accept a PR without merging it directly into `master`, therefore allowing CI to run without affecting production builds.
1. **Set up Commitizen**
  With a popular repo like this, there are *a lot* of different contributors, each with their own style of writing. This is great because it means more features get created faster and more bugs get fixed sooner, but it also makes it really hard to review commits just based on their messages. [Commitizen](https://commitizen.github.io/cz-cli/) helps out by forcing contributors to use a standard commit message format.
1. **Set up `semantic-release`**
  [`semantic-release`](https://github.com/semantic-release/semantic-release) automates the entire process of version bumping, changelog generation, and publishing to package managers (like npm). It's a great thing to [set up with CI](https://github.com/semantic-release/semantic-release#automation-with-ci) because, as they say in their README:
    > ...releases are guaranteed to be [unromantic and unsentimental](http://sentimentalversioning.org/).

Again, I don't want to step on your feet so let me know if you want me to chip in on this one. 😉

**Comment by BcRikko** [comment]
I have not started this issue yet.
I'm the first time that I became the owner of a product that many people pay attention.  😨 

so, please help me 🙏 
and could you give me some advice please? 🙏

**Comment by trezy** [comment]
@BcRikko of course! I did fork and start working on setting up CI this afternoon. You can check out what I’ve got so far on my fork: https://github.com/trezy/NES.css/blob/master/.circleci/config.yml

**Comment by BcRikko** [comment]
oh, Thanks 🎉🎉🎉

**Comment by montezume** [comment]
How about adding the built css to gitignore once this is done? 🙏

**Comment by BcRikko** [comment]
I agree 👍 
It's too much hassle to resolve conflicting files resolve... 😢 

so, I'd like to build CSS(dist files) with CI. 🛠

**Comment by montezume** [comment]
Yes, let CI build css.

![Image of bender](https://github.com/semantic-release/semantic-release/raw/master/media/bender.png)

**Comment by trezy** [comment]
Yup, I'm working on getting `semantic-release` set up right now. Once that's done I'll make the PR, then we can make separate issues to cover adding release targets (cdnjs, npm, etc). Once that's done, it'll make sense to remove the compiled CSS files from the repo. 😁
