### ISSUE TITLE
Code of conduct

### ISSUE THREAD

**Issue by 4k1k0** [nostalgic-css/NES.css#137]
Are you considering adding a coc for this project? :thinking:

**Comment by evexoio** [comment]
@4k1k0 Yes, we got this [request before](https://github.com/nostalgic-css/NES.css/issues/25#issue-385752198).

We want to do that but we're quite busy at the moment making sure everything works from ci and releasing to tests.

Can you help and layout a template and we'll add to what you've done?

**Comment by trezy** [comment]
Actually, @evexoio, this is slightly different from the CONTRIBUTING.md and it's something I've been meaning to mention as well. A code of conduct defines the behaviors we expect — as well as the behaviors we won't tolerate — from contributors. I usually use the [Contributor Covenant][contributor-covenant] for my repos.

@BcRikko, what are your thoughts?

[contributor-covenant]: https://www.contributor-covenant.org/version/1/4/code-of-conduct.html

**Comment by BcRikko** [comment]
I'm not sure much about it. Are `Code of conduct` and `Contributor Covenant` different? 🤔 

I looked at other projects, and then I think that it's good to use `Contributor Covenant`. 👍 

* nodejs: https://github.com/nodejs/admin/blob/master/CODE_OF_CONDUCT.md
* vuejs: https://github.com/vuejs/vue/blob/dev/.github/CODE_OF_CONDUCT.md
* bootstrap: https://github.com/twbs/bootstrap/blob/v4-dev/CODE_OF_CONDUCT.md

**Comment by trezy** [comment]
@BcRikko Nope, the Contributor Covenant is just one of the Codes of Conduct that a lot of projects use. Some projects use their own homegrown versions, but I'm a big fan of the Contributor Covenant.

**Comment by 4k1k0** [comment]
@BcRikko [`Contributor covenant`](https://www.contributor-covenant.org) is the name of a popular code of conduct. You can check out the tempalte [here](https://www.contributor-covenant.org/version/1/4/code-of-conduct). Some projects and organizations write their own coc as well. :smiley:

**Comment by BcRikko** [comment]
I see, Thanks 🙇 

I can not make difficult sentences, because I'm not good at English.
It is difficult for me to make own homegrown version. 😖 
so let's use `Contributor Covenant` 👍 
Is it OK? 🤔 

I just hope for everyone to have fun 😆✨

**Comment by 4k1k0** [comment]
Perfect! I wanted to make the proposal through githuub, but one of the requirements is an email adress to fill the template. So I think it's better if @BcRikko or someone of the community do it. :smile:

**Comment by trezy** [comment]
Yeah, I was thinking about that, @4k1k0. I think it should definitely be @BcRikko for now, but it’d be great if we grab a domain and set up a support email that we can have go to the team.

**Comment by BcRikko** [comment]
How about accepting contact at Gitter? 🤔 

> Instances of abusive, harassing, or otherwise unacceptable behavior may be reported by contacting the project team at [INSERT EMAIL ADDRESS]. 

↓↓↓

Instances of abusive, harassing, or otherwise unacceptable behavior may be reported by contacting `@BcRikko` of the project team on [Our Gitter](https://gitter.im/nostalgic-css).

**Comment by jjspace** [comment]
Generally the place to report abusive things or harassment happens with a more private/secure method. I know I wouldn't really want to go to report a problem like that to a public chat that the offender could also have access to.

**Comment by 4k1k0** [comment]
I'm not sure what Gitter is. It looks like Slack to me, Is there a chance there could be a special account for that purpose on the Gitter and can receive direct messages? Although I'm not sure, does that means that if you want to contribute to the project you have to set up a Gitter account? 🤔

**Comment by trezy** [comment]
@jjspace Agreed, it's generally helpful to be able to report issues privately. One issue with having a single email, though, is that the one person listed may also be the person causing the problem. That leaves the person reporting with no avenue to report issues.

I very seriously doubt that @BcRikko would be a person to cause issues, and even if they were this *is* their project. Even still, it's probably better to make sure that there are multiple options for contacts. I'd be okay with adding the core team's emails to the document. Mine is exposed via several Codes of Conduct across Github, though some of the members of our core team may not be so keen on exposing their email address.

@evexoio, @evexoio, @BcRikko: What are your thoughts on adding each of our emails to the Code of Conduct? If only a couple of us are willing to add our emails, I think that's fine. Another alternative is that we grab a domain and create emails for each of us with it, as well as a general support email. I actually have a domain that I've been eyeing for us, so that's an option.

**Comment by guastallaigor** [comment]
You can add my e-mail to the Code of Conduct, that's fine by me.
In fact, it's displayed in my Github profile 😄

**Comment by BcRikko** [comment]
Ok, you can also add my e-mail to the Code of Conduct 👍 
b.c.rikko@gmail.com 📬

**Comment by evexoio** [comment]
Closing since this is done, https://github.com/nostalgic-css/NES.css/blob/develop/CODE_OF_CONDUCT.md
