### ISSUE TITLE
[Suggestion] Make a class for thumbnails

### ISSUE THREAD

**Issue by 4k1k0** [nostalgic-css/NES.css#206]
I would like to see something like bootstrap's thumbnails. Something like this:

    <img src="image.jpg" class="nes-thumbnail">

It can even have different styles

    <img src="image.jpg" class="nes-thumbail mario">

to get something like this

![2018-12-18 11_33_34-window](https://user-images.githubusercontent.com/3821782/50171771-ef16d600-02b8-11e9-98e8-57ef43bee0fd.jpg)

If you like the idea I can work on it.

**Comment by evexoio** [comment]
@4k1k0 I don't really get what you're suggesting 🙈

Can you please add more examples or describe a bit more what we're adding here?

**Comment by 4k1k0** [comment]
Bootstrap has a CSS class for thumbnails, which gives a border to a `<img>` tag so it can looks like if it has a frame.

![2018-12-18 16_02_40-a pen by wako](https://user-images.githubusercontent.com/3821782/50185747-627f0e80-02de-11e9-8957-4478801dcf15.jpg)

It would be cool if NES.css has something similar to this. It could be like the squares in Mario Bros 3 and even another games.

![mario bros 3](https://user-images.githubusercontent.com/3821782/50171771-ef16d600-02b8-11e9-98e8-57ef43bee0fd.jpg)

What do you think?

**Comment by guastallaigor** [comment]
I don't think we will accepting this, at least not right now. The idea of the framework is to keep it smaller as possible. See the image below:

![image](https://user-images.githubusercontent.com/22016005/53744075-035f7d80-3e7b-11e9-8094-6f1012e35564.png)

This image is not suited for all components but will give you a general ideia. Sorry about the delay, this issue was misundestood about the members and a bit lost in here.
