### ISSUE TITLE
is-dark input

### ISSUE THREAD

**Issue by juanpablolvl99** [nostalgic-css/NES.css#248]
Is just a question, why don't have a is-dark to inputs? would be nice use inputs inside of dark containers in the same color scheme.

ps.: sorry about my english, i hope you can understand my question.

**Comment by guastallaigor** [comment]
Hello @juanpablolvl99 , we don't have it simply because no one made it :smile:. Contributions are welcome!
In case you want to develop it, create a new Issue using the issue template (Feature request) and comment that you are developing it.
Any other question just let us know. I can reopen this issue.
Thank you.
