### ISSUE TITLE
nes-avatar add image-rendering pixelated

### ISSUE THREAD

**Issue by yamanoku** [nostalgic-css/NES.css#259]
**Is your feature request related to a problem? Please describe.**

I was concerned that only the avatar image is rendering smoothly among the components of the dot.

**Describe the solution you'd like**

```
.nes-avatar {
    image-rendering: pixelated;
}
```

**Additional context**
Although it may not have a big influence, I thought that it might be able to offer something close to the value of NES.css when I put it in.

However, Can I Use says that since browser is not fully compatible, I don't think there is anything easy to introduce.
https://caniuse.com/#feat=css-crisp-edges

Please consider about this Issue :-)

**Comment by BcRikko** [comment]
Thanks for your issue 🙇 
That's a good point.👍 

But `image-rendering` depends on the user's image file and thing users want to do.
So It seems beter to set `image-rendering` in inline style instead of adding to `nes-avatar`.🤔

I'll try on the demo page as follows: https://github.com/nostalgic-css/NES.css/pull/277#issuecomment-461852242
![](https://user-images.githubusercontent.com/5305599/52489585-f9dd4f80-2c05-11e9-9116-9227f057c698.png)
