### ISSUE TITLE
Add sample code to the demo page

### ISSUE THREAD

**Issue by BcRikko** [nostalgic-css/NES.css#269]
I want to sample code on demo page.

**Is your feature request related to a problem? Please describe.**
It's hard to read HTML and CSS to use NES.CSS.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

![127 0 0 1_5500_index html](https://user-images.githubusercontent.com/5305599/52031056-f68af980-255d-11e9-8b5e-3476d9f24703.png)

**Comment by guastallaigor** [comment]
In my opinion it is better if we have a show/hide code, and it is hidden by default, because sometimes people just want to checkout the components first. 
And maybe another button to copy code to clipboard...

What do you think?

**Comment by LunarDevelopment** [comment]
Either way it needs implemented ASAP, this framework is awkward as hell to use by just inspecting source all the time. 

In addition to code snipits I think it'd be great to have a boilerplate to start projects with (just bog standard html, head body with a few standard components like nav, panel, form fields with submit) 

Just imo.

**Comment by guastallaigor** [comment]
Yes, I agree with the first part, ref #180.
 Not sure about the boilerplate tho, because usually it has JS involved and we don't offer any. And this days people are using JS frameworks, and their CLIs, so it's kind of hard to create a boilerplate that suits for everyone.
You could use wrappers for [vue](https://github.com/jefer590/vuenes.css) and [react](https://github.com/bschulte/nes-react) that can help you to build some projects using NES.css.

**Comment by BcRikko** [comment]
It will be completed soon. 🛠 
![demo](https://user-images.githubusercontent.com/5305599/52576109-d6fba700-2e62-11e9-9255-6b58c9b8da77.gif)
