### ISSUE TITLE
Remove Nintendo's character icon

### ISSUE THREAD

**Issue by BcRikko** [nostalgic-css/NES.css#304]
Nintendo owns the copyright of some pixel art. Therefore, we need to remove some style.

* nes-mario
* nes-ash
* nes-pokeball
* nes-bulbasaur
* nes-charmander
* nes-squirtle
* nes-kirby

However, there are sites that use these.
So it should be deprecated and should be deleted in the near future.

**Comment by guastallaigor** [comment]
If I can say something about this, I would be against it. I may be biased, because I create a lot of them 😄, but I have a few things to say about this. Note that this is my personal opinion and I don't know much about copyright infringements.

- Even so Nintendo owns the copyright, this is a OSS project available to all, and the icons is no more different than 8bit images/pictures/draws that people create and use it on the internet.
- At first, these icons would be a playground kind of thing, but I notice already a lot of sites using these, and more and more sites are using, like blogs, personal portfolios, events, and so on. Before this issue I was thinking of a way to create even more icons and separate them in NES.icons.
- There's already a lot of programming related content that uses pokémons for example, like APIs, bots, services, and so on. So that brings the question. The copyright situation only applies to the picture/draw of the pokémon?
- Before removing them, we should look deeper into the copyright can and can't policy. The framework is getting more popularity, but I don't think has that amount of popularity that Nintendo would care.
- Also we could maybe be able to bend the rules a little, like changing the names of the icons, and even some colors if necessary to not have to remove then. Or separate into another project, so if there's some problem we only would "lose" the rights of that project, and not this one.

I could talk a lot more about this, but I think you can get the general idea here. Then again, this is just my personal thoughts about this situation.

**Comment by BcRikko** [comment]
I understand how you feel. 👍 
I know, many sites use pixel arts, and these arts are very attractive.

I read "Nintendo Game Content Guidelines for Online Video & Image Sharing Platforms"
https://www.nintendo.co.jp/networkservice_guideline/en/index.html

> Q6:Can I create, upload, and livestream content that is based on other Nintendo intellectual property, outside of gameplay footage and screenshots (such as, fan art)?
> 
> A6:The Guidelines only cover the sharing of Nintendo Game Content on appropriate video and image sharing sites. Any other use of Nintendo's intellectual property and creation of content outside of this scope is subject to the relevant laws of the applicable jurisdiction. Nintendo cannot provide legal advice to you, so we encourage you to seek your own legal counsel if you have any questions about whether your particular proposed use is permitted.

It's legal gray areas problem.

"appropriate video and image sharing sites" are YouTube, Twitter,  Twitch, Instagram, Niconico Douga. GitHub is not included in these sharing sites. 

So we need to comply with the laws of each country. 🤔 
Even if it does not remove pixel arts, we need to call attention to NES.css users. 📣

**Comment by guastallaigor** [comment]
Thank you for hearing me out. I've just read the "Nintendo Game Content Guidelines for Online Video & Image Sharing Platforms" and indeed there's some implications there like you've mentioned, but also there's this:

> A3:We generally accept most commonly used video and image sharing platforms such as, **but not limited to**, YouTube, Twitch, and Instagram. However, we reserve the right to remove any content that we believe is unlawful, infringing, inappropriate, or not in line with the Guidelines.

Maybe something like Github was never brought to their attention :thinking: , and they may agree with our kind of "image sharing". But I understand a little more now, and I see that this can go bad in the future, so I agree with whatever you want to do with those icons, either removing them or just warning the users :+1:

**Comment by BcRikko** [comment]
> they may agree with our kind of "image sharing".

I see. 👍 

But it's difficult for me to completely understand the laws, especially the copyright. :sweat: 
Because there are different ways to interpret it.

So let's start with writing notes first. like this:
https://github.com/nostalgic-css/NES.css/pull/292#issuecomment-466722696
