### ISSUE TITLE
Markup bug at https://nostalgic-css.github.io/NES.css/

### ISSUE THREAD

**Issue by vitalitt** [nostalgic-css/NES.css#306]
Dark checkbox example is invisible:
![image](https://user-images.githubusercontent.com/35432215/53352186-fdbde100-392a-11e9-820a-505addb7bba1.png)
after selecting: 
![image](https://user-images.githubusercontent.com/35432215/53352213-0adad000-392b-11e9-9b31-442c97a4fb2c.png)

**Comment by guastallaigor** [comment]
If I can explain myself, It was the fastest way that I did to show the `is-dark` class option inside the code button, when we were refactoring the demo page for v2.0.0 :smile:, I apologize for that.

But I agree this is wrong in many ways. It's fixed in #292, and will be launched in the next release #305.
I will be closing this now but reopen if necessary. Thank you.
