### ISSUE TITLE
CodePen icon

### ISSUE THREAD

**Issue by lalaithan** [nostalgic-css/NES.css#310]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
An icon for CodePen

**Describe alternatives you've considered**
Font Awesome

**Additional context**

**Comment by sazzadsazib** [comment]
I think we should split CSS file for some icons that is not much used... suggestions? Else main CSS would be heavy after some time..

**Comment by lalaithan** [comment]
An idea to consider in regards to keeping the CSS file size under control is to have a brief section explaining how to do it manually.

**Comment by sazzadsazib** [comment]
We can have separate CSS file for icons like codepen, also can add more icons there. thoughts?

**Comment by guastallaigor** [comment]
When we start having a lot more icons, the idea was to move to another project, [NES.icons](https://github.com/nostalgic-css/NES.icons). 

The idea back then was to have 8-bit icons, but as SVG, not only as `border-image/box-shadows`.
But had a few issues with that, and the member that was creating the SVG's, I'm not sure if he is still active in this project.

I like this idea to split all icons into another project because of the things you guys already said, to reduce the core size and the possibility to add more, as SVG or the way they are now, but carrefully because of  copyright infringements (ref #304).

I know you're busy @BcRikko, but when you got some time please share your thoughts into this.

**Comment by BcRikko** [comment]
Sry, I'm late... 🙇 

I think that the idea of split the icon  into another project is good 👍 
But I have no time to do it.

In fact, I wish I accepted the idea of everyone's icon.
But adding just one icon will increase the CSS file size.
So I'd like to accept only relatively important icons for everyone to use.

If you really need to use a new icon, I recommend you to use the following tool to create your icons. 🎨 
https://vue-pixel-art.now.sh/
