### ISSUE TITLE
Radios has stray pixels in Firefox

### ISSUE THREAD

**Issue by Polygonalr** [nostalgic-css/NES.css#39]
![image](https://user-images.githubusercontent.com/16399656/49277391-688e8600-f4bc-11e8-8a97-ebb8597f27c3.png)
Stray pixels appear when Radio cursor is blinking.

Does not appear in Google Chrome, the pixels appear in Firefox 63.0.3, even with different zoom levels.
Might just be a Firefox bug.

**Comment by BcRikko** [comment]
Thanks. 

I see... but, I don't know how to resolve the problem. 😭 
Please help me 🙏 

Chrome70: zoom to 110%
![2018-11-30 17 48 49](https://user-images.githubusercontent.com/5305599/49278501-57e40d00-f4c8-11e8-8726-93f362820d72.png)
![2018-11-30 17 49 08](https://user-images.githubusercontent.com/5305599/49278503-57e40d00-f4c8-11e8-82db-c8728ad43bcb.png)

**Comment by alexgleason** [comment]
I know how to fix this, sending a PR shortly.

**Comment by alexgleason** [comment]
Wait are you talking about the white lines or the dots between the choices? My PR is for the dots between the choices, whoops.

**Comment by ernestomancebo** [comment]
hi @BcRikko & @Polygonalr, please take a look into my PR; somehow firefox separates the boxes and needs spread-radius to be specified.

**Comment by BcRikko** [comment]
@ernestomancebo Thanks 🙇 
I merged #45 👍

**Comment by ernestomancebo** [comment]
Any time @BcRikko. I'll be rambling among the issues of this repo, I really like this project.

**Comment by myfonj** [comment]
Glad to see this resolved :]

I think that change from last PR could be simplified: `spread` introduced in shadows could be added to base dimensions of shadowed square, so that original
`…::before{ width: 2px; height: 2px; top: -2px; left: -2px; /* box shadow with .32px spread */}`
becomes
`…::before{ width: 2.64px; height: 2.64px; top: -2.32px; left: -2.32px; /* box shadow without spread, so ommitable */}`
 (BTW, why was that spread expressed in `em`s?)

Related: I've compared several alternative methods of embedding such content in CSS, focusing on data size ( https://codepen.io/myf/pen/EOGBLY/?editors=0100 ) and so far it seems that what is currently done in ~3772 bytes of box-shadow (what could be ~2211 b after aforementioned adjustment) could be as well done in ~506 b SVG dataURI or ~347 b PNG dataURI.

**Comment by ernestomancebo** [comment]
@myfonj did you tried that on google chrome or safari? increasing the box shadow size works on FF, but not in the others.

**Comment by Polygonalr** [comment]
Whoops, I apologise for the lack of updates and not elaborating about the issue better.

I've checked the updated project, and I am glad the radio arrow is fixed in Firefox. However, the stray pixel still remains as seen from the screenshot below:
![image](https://user-images.githubusercontent.com/16399656/49348227-3446df80-f6df-11e8-91ba-9d3ebf43a3c5.png)

I'm not too sure whether anyone else can reproduce this bug in Firefox.
I've taken a look at the code but still can't find out what causes it. Maybe someone else who is better with SCSS can help out?
