### ISSUE TITLE
Buttons color Error

### ISSUE THREAD

**Issue by JMGama** [nostalgic-css/NES.css#74]
The color of the buttons stays the same when you click it then you need to click other place to restore the original button color.
It's a little hard to explain.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/25947269/49463207-7f372480-f7bd-11e8-9d94-0f8fb99bab73.gif)

**Comment by JMGama** [comment]
The button has a click function that ends and the button remains the same color, is that okay?

**Comment by jjspace** [comment]
It's because of how the styling is applied. It's changing the color on `:focus` of the button. Focus persists even after a click is done until you *focus*/click on something else. We could take the styling off of focus and just have it change on `:hover` and `:active` and this wouldn't happen. I personally think this might be better but that could be open to discussion.

**Comment by fleeting** [comment]
This is just because the hover and focus states use the same styles. For accessibility we should tweak the focus state to be different from the hover and normal state.

Ultimately what's happening is the inset style is from the active state, which happens when you click in. However, just like when you tab through the buttons with the keyboard, your focus is now on that button from the click and since focus and hover use the same styles - it just style looks the same.

We shouldn't remove focus but it's worth giving it it's own style.

**Comment by jjspace** [comment]
+1 for thinking of tab focus, I'd forgotten about that. In that case I think it might be best to keep the hover and focus styling the same for consistency right?

**Comment by evexoio** [comment]
I've tried reproducing this on safari and chrome(both OSX) but couldn't reproduce it.
Which browser are you on?

**Comment by fleeting** [comment]
I get it in Chrome on OS X, it's just the focus styles. https://github.com/nostalgic-css/NES.css/blob/master/scss/elements/buttons.scss#L6 should ideally be split up so focus has it's own unique styles different than the hover style.

**Comment by jjspace** [comment]
I can confirm that this happens in Chrome 70 on OSX and Chrome 70, FF 63 and Edge on Windows. However for some reason it does not seem like Safari and FF 63 keep focus state when you stop hovering on OSX so this problem does not exist there. 
I think it _might_ be worth separating the styles to handle them independently but with the fact that tab focus is essentially the mouse-less equivalent of hover I think they should stay the same style if not very similar. The "bug" just has to do with how browsers handle focus state and not really something we could get around while maintaining similar styles for both

**Comment by evexoio** [comment]
I see.
@fleeting are you still going to open a PR for this issue? 🙈

**Comment by youngkaneda** [comment]
so what would be better, remove the effect in focus, or add a different focus effect? Since they are the same.

**Comment by BcRikko** [comment]
> https://github.com/nostalgic-css/NES.css/blob/master/scss/elements/buttons.scss#L6 should ideally be split up so focus has it's own unique styles different than the hover style.

I agree 👍 

---

I splitted the focus and hover styles. ✂️ 

![focus](https://user-images.githubusercontent.com/5305599/59237792-745ec000-8c36-11e9-843f-f0dd3dfa74ee.gif)

```scss
// buttons.scss
@mixin btn-style($color, $background, $hover-background, $shadow) {
  //...
  &:focus {
    box-shadow: 0 0 0 6px rgba($shadow, 0.3);
  }
  //...
}
```

**Comment by youngkaneda** [comment]
a simple and great solution
